// app2/client/Layout.svelte
<script lang="ts">
	import type { Corner, PaneProps, Axe } from './helpers/Layout';
	import { Layout } from './helpers/Layout';
	import { nanoid } from 'nanoid';
	import { onMount } from 'svelte';

	export let panes: PaneProps[];

	let layoutRef: HTMLDivElement | undefined;
	let bounds = new DOMRect();
	let dragging = false;
	let dragLeft: string | undefined;
	let dragRight: string | undefined;
	let dragCorner: Corner | undefined;
	let dragBounds = new DOMRect();
	let dragSiblings = false;
	let divId: number | undefined;
	let divAxe: Axe | undefined;
	let lastPointerEvent: PointerEvent | undefined;
	let trottledPointerEvent: PointerEvent | undefined;
	let layout = new Layout(panes);

	console.log('Layout', layout);

	onMount(() => {
		onResize();
	});

	function onResize() {
		bounds = layoutRef!.getBoundingClientRect();
	}

	function onLeave() {
		if (dragging) {
			dragging = false;

			const newPanes = panes.reduce((panes, pane) => {
				const layoutPane = layout.panes.find(p => p.id === pane.key);
				if (layoutPane && layoutPane.width > 0 && layoutPane.height > 0) {
					pane.top = layoutPane.top;
					pane.right = layoutPane.right;
					pane.bottom = layoutPane.bottom;
					pane.left = layoutPane.left;
					panes.push(pane);
				}
				return panes;
			}, [] as PaneProps[]);

			console.log('onChange', newPanes);
			// TODO onChange && onChange(newPanes);
		}
	}

	function onMove(e: PointerEvent) {
		if (dragging) {
			if (e.clientX === lastPointerEvent?.clientX && e.clientY === lastPointerEvent?.clientY) {
				return;
			}
			lastPointerEvent = e;
			trottledPointerEvent = trottledPointerEvent ?? e;

			const { x: oX, y: oY, width, height } = bounds;
			const [x, y] = [e.clientX - oX, e.clientY - oY];
			const [pX, pY] = [x / width * 100, y / height * 100];
			const [cX, cY] = [
				Math.max(Math.min(pX, dragBounds.right), dragBounds.left),
				Math.max(Math.min(pY, dragBounds.bottom), dragBounds.top),
			];

			if (dragCorner !== undefined) {
				const deltaX = e.clientX - trottledPointerEvent.clientX;
				const deltaY = e.clientY - trottledPointerEvent.clientY;

				if (deltaX * deltaX + deltaY * deltaY >= 20 * 20) {
					trottledPointerEvent = e;

					const axe = Math.abs(deltaX) > Math.abs(deltaY) ? 'vertical' : 'horizontal';

					if (axe !== divAxe) {
						divAxe = axe;

						const newPanes = panes.reduce((panes, pane) => {
							const newPane = { ...pane };
							if (newPane.key === dragLeft || newPane.key === dragRight) {
								newPane.top = dragBounds.top;
								newPane.right = dragBounds.right;
								newPane.bottom = dragBounds.bottom;
								newPane.left = dragBounds.left;

								if (axe === 'horizontal') {
									newPane[newPane.key === dragLeft ? 'bottom' : 'top'] = cY;
								} else {
									newPane[newPane.key === dragLeft ? 'right' : 'left'] = cX;
								}
							}
							panes.push(newPane);
							return panes;
						}, [] as PaneProps[]);

						console.log('onChange', newPanes);
						// TODO : onChange && onChange(newPanes);
						return;
					}
				}
			}

			if (dragLeft !== undefined && dragRight !== undefined) {
				const edge = layout.edges.find(e => e.left.id === dragLeft && e.right.id === dragRight);
				if (edge) {
					const p = edge.axe === 'horizontal' ? cY : cX;
					
					edge.p = p;
					edge.updateDOM();

					if (dragSiblings) {
						for (const sibling of edge.allSiblings()) {
							sibling.p = p;
							sibling.updateDOM();
						}
					}

					const newPanes = panes.map(pane => {
						const newPane = { ...pane };
						const layoutPane = layout.panes.find(p => p.id === pane.key);
						if (layoutPane) {
							newPane.top = layoutPane.top;
							newPane.right = layoutPane.right;
							newPane.bottom = layoutPane.bottom;
							newPane.left = layoutPane.left;
						}
						return newPane
					});

					console.log('onDragging', newPanes);
					// TODO
					// onDragging && onDragging(panes.map(pane => {
					// 	const newPane = { ...pane };
					// 	const layoutPane = layout.panes.find(p => p.id === pane.key);
					// 	if (layoutPane) {
					// 		newPane.top = layoutPane.top;
					// 		newPane.right = layoutPane.right;
					// 		newPane.bottom = layoutPane.bottom;
					// 		newPane.left = layoutPane.left;
					// 	}
					// 	return newPane
					// }));
				}
			}
		}
	}

	function onResizerDown(id: number) {
		return (e: PointerEvent) => {
			e.preventDefault();
			e.stopPropagation();

			const edge = layout.edges[id];
			let minX: number = 0;
			let maxX: number = 100;
			let minY: number = 0;
			let maxY: number = 100;
			const breakable = edge.axe === 'horizontal'
				? Math.abs(edge.left.left - edge.right.left) < 0.1 && Math.abs(edge.left.right - edge.right.right) < 0.1
				: Math.abs(edge.left.top - edge.right.top) < 0.1 && Math.abs(edge.left.bottom - edge.right.bottom) < 0.1;

			for (const sibiling of [edge].concat(edge.allSiblings())) {
				minX = Math.max(minX, sibiling.left.left);
				maxX = Math.min(maxX, sibiling.right.right);
				minY = Math.max(minY, sibiling.left.top);
				maxY = Math.min(maxY, sibiling.right.bottom);
			}

			dragging = true;
			dragLeft = edge.left.id;
			dragRight = edge.right.id;
			dragBounds = new DOMRect(minX, minY, maxX - minX, maxY - minY);
			dragSiblings = !(breakable && e.ctrlKey);
		}
	}

	function onDividerDown(id: number, corner: Corner) {
		return (e: PointerEvent) => {
			e.preventDefault();
			e.stopPropagation();

			const pane = layout.panes[id];

			const paneProps: PaneProps = panes.find(p => p.key === pane.id)!;
			const newPaneProps: PaneProps = { ...paneProps };
			newPaneProps.key = nanoid();

			dragLeft = pane.id;
			dragRight = newPaneProps.key;

			if (corner === 'top-left' || corner === 'bottom-left') {
				let t = dragLeft;
				dragLeft = dragRight;
				dragRight = t;
				paneProps.left += 1;
				newPaneProps.right = paneProps.left;
			} else {
				paneProps.right -= 1;
				newPaneProps.left = paneProps.right;
			}

			dragging = true,
			dragCorner = corner;
			dragBounds = new DOMRect(pane.left, pane.top, pane.right - pane.left, pane.bottom - pane.top);
			divAxe = 'vertical';

			console.log('onChange', panes.concat([newPaneProps]));
			// TODO onChange && onChange(panes.concat([newPaneProps]));
		}
	}
</script>

<svelte:window on:resize={onResize} />
<svelte:body on:pointerup={onLeave} on:pointermove={onMove} />

<div bind:this={layoutRef} class="layout">
	<div class="container">
		{#each layout.edges as edge, id (edge.id)}
			<div
				bind:this={edge.ref}
				on:pointerdown={onResizerDown(id)}
				class={`resizer resizer--${edge.axe}`}
				style={edge.axe === 'horizontal'
						? `top: ${edge.p.toFixed(6)}%; left: ${edge.s.toFixed(6)}%; width: ${(edge.e - edge.s).toFixed(6)}%; height: var(--edge-size);`
						: `top: ${edge.s.toFixed(6)}%; left: ${edge.p.toFixed(6)}%; width: var(--edge-size); height: ${(edge.e - edge.s).toFixed(6)}%;`}
			/>
		{/each}
	</div>
	<div class="container">
		{#each layout.panes as pane, id (pane.id)}
			<div
				bind:this={pane.dividerRef}
				class="divider"
				style={`top: ${pane.top.toFixed(6)}%; right: ${(100 - pane.right).toFixed(6)}%; bottom: ${(100 - pane.bottom).toFixed(6)}%; left: ${(pane.left).toFixed(6)}%; border-width: ${pane.links.map((link, dir) => link ? (dir === 1 || dir === 2 ? `var(--border-size)` : 0) : `var(--border-size)`).join(' ')};`}
			>
				<div on:pointerdown={onDividerDown(id, 'top-left')} class="divider--top-left" />
				<div on:pointerdown={onDividerDown(id, 'top-right')} class="divider--top-right" />
				<div on:pointerdown={onDividerDown(id, 'bottom-left')} class="divider--bottom-left" />
				<div on:pointerdown={onDividerDown(id, 'bottom-right')} class="divider--bottom-right" />
			</div>
		{/each}
	</div>
	<div class="container">
		{#each layout.panes as pane (pane.id)}
			<div
				bind:this={pane.paneRef}
				class="view"
				style={`top: ${pane.top.toFixed(6)}%; right: ${(100 - pane.right).toFixed(6)}%; bottom: ${(100 - pane.bottom).toFixed(6)}%; left: ${pane.left.toFixed(6)}%; --pane-top-neighbor: ${pane.links[0].length ? 1 : 0}; --pane-right-neighbor: ${pane.links[1].length ? 1 : 0}; --pane-bottom-neighbor: ${pane.links[2].length ? 1 : 0}; --pane-left-neighbor: ${pane.links[3].length ? 1 : 0};`}
			>
				View
			</div>
		{/each}
	</div>
</div>

<style>
	.layout {
		position: relative;
		display: flex;
		flex: 1;
		--edge-size: 10px;
		--subdivide-size: 10px;
		--border-size: 1px;
	}

	.container {
		position: absolute;
		width: 100%;
		height: 100%;
		pointer-events: none;
	}

	.view {
		--pane-top-neighbor: 0;
		--pane-right-neighbor: 0;
		--pane-bottom-neighbor: 0;
		--pane-left-neighbor: 0;
		position: absolute;
		overflow: hidden;
		pointer-events: auto;
	}

	.resizer {
		position: absolute;
		z-index: 35;
		touch-action: none;
		pointer-events: auto;
	}

	.resizer--horizontal {
		cursor: var(--cursor-ns-resize);
		top: 0;
		height: 100%;
		width: var(--edge-size);
		transform: translateY(calc(var(--edge-size) / -2));
	}

	body.key--alt .resizer--horizontal {
		cursor: var(--cursor-swap-horizontal);
	}

	.resizer--vertical {
		cursor: var(--cursor-ew-resize);
		left: 0;
		width: 100%;
		height: var(--edge-size);
		transform: translateX(calc(var(--edge-size) / -2));
	}
	
	body.key--alt .resizer--vertical {
		cursor: var(--cursor-swap-vertical);
	}

	.divider {
		position: absolute;
		pointer-events: none;
	}

	.divider--top-left,
	.divider--top-right,
	.divider--bottom-left,
	.divider--bottom-right {
		position: absolute;
		z-index: 35;
		touch-action: none;
		pointer-events: auto;
		width: var(--subdivide-size);
		height: var(--subdivide-size);
	}

	.divider--top-left {
		top: 0;
		left: 0;
		cursor: var(--cursor-nw-resize);
	}

	.divider--top-right {
		top: 0;
		right: 0;
		cursor: var(--cursor-ne-resize);
	}

	.divider--bottom-left {
		bottom: 0;
		left: 0;
		cursor: var(--cursor-sw-resize);
	}

	.divider--bottom-right {
		bottom: 0;
		right: 0;
		cursor: var(--cursor-se-resize);
	}
</style>

// app/client/containers/Layout.tsx
import React, { useState, useEffect, useRef, useMemo } from 'react';
import { nanoid } from 'nanoid';
import './Layout.scss';

export interface PaneProps {
	key: string,
	top: number,
	right: number,
	bottom: number,
	left: number,
	minWidth?: number,
	minHeight?: number,
	elem: React.ReactElement,
	props?: any,
}

export interface LayoutProps {
	panes: PaneProps[],
	onChange: (panes: PaneProps[]) => void,
}

type Axe = 'horizontal' | 'vertical';

interface Internal {
	bounds: DOMRect,
	dragging: boolean,
	dragLeft?: string,
	dragRight?: string,
	dragCorner?: Corner,
	dragBounds: DOMRect,
	dragSiblings?: boolean,
	divId?: number,
	divAxe?: Axe,
	lastPointerEvent?: PointerEvent,
	trottledPointerEvent?: PointerEvent,
}

export default function({ panes, onChange }: React.PropsWithChildren<LayoutProps>) {
	const layoutRef = useRef<HTMLDivElement>(null);
	const internal = useRef<Internal>({
		bounds: new DOMRect(),
		dragging: false,
		dragBounds: new DOMRect(),
	});
	const layout = useMemo<Layout>(
		() => new Layout(panes),
		[panes]
	);

	useEffect(() => {
		internal.current.bounds = layoutRef.current?.getBoundingClientRect()!;

		function onResize(_: UIEvent) {
			internal.current!.bounds = layoutRef.current?.getBoundingClientRect()!;
		}

		function onLeave(e: PointerEvent) {
			if (internal.current?.dragging) {
				internal.current = {
					...internal.current!,
					dragging: false,
					dragLeft: undefined,
					dragRight: undefined,
					dragCorner: undefined,
					dragSiblings: undefined,
					divId: undefined,
					divAxe: undefined,
				};

				const newPanes = panes.reduce((panes, pane) => {
					const layoutPane = layout.panes.find(p => p.id === pane.key);
					// Remove missing pane or collapsed pane
					if (layoutPane && layoutPane.width > 0 && layoutPane.height > 0) {
						pane.top = layoutPane.top;
						pane.right = layoutPane.right;
						pane.bottom = layoutPane.bottom;
						pane.left = layoutPane.left;
						panes.push(pane);
					}
					return panes;
				}, [] as PaneProps[]);


				onChange(newPanes);
			}
		}

		function onMove(e: PointerEvent) {
			if (internal.current?.dragging === true) {
				const { bounds, dragLeft, dragRight, dragBounds, dragCorner, dragSiblings, divAxe, lastPointerEvent, trottledPointerEvent } = internal.current;

				if (e.clientX === lastPointerEvent?.clientX && e.clientY === lastPointerEvent?.clientY) {
					return;
				}
				internal.current.lastPointerEvent = e;
				internal.current.trottledPointerEvent = trottledPointerEvent ?? e;

				const { x: oX, y: oY, width, height } = bounds;
				const [x, y] = [e.clientX - oX, e.clientY - oY];
				const [pX, pY] = [x / width * 100, y / height * 100];
				const [cX, cY] = [
					Math.max(Math.min(pX, dragBounds.right), dragBounds.left),
					Math.max(Math.min(pY, dragBounds.bottom), dragBounds.top),
				];

				if (dragCorner !== undefined) {
					const { trottledPointerEvent } = internal.current;
					const deltaX = e.clientX - trottledPointerEvent.clientX;
					const deltaY = e.clientY - trottledPointerEvent.clientY;

					if (deltaX * deltaX + deltaY * deltaY >= 20 * 20) {
						internal.current.trottledPointerEvent = e;

						const axe = Math.abs(deltaX) > Math.abs(deltaY) ? 'vertical' : 'horizontal';

						if (axe !== divAxe) {
							internal.current.divAxe = axe;

							const newPanes = panes.reduce((panes, pane) => {
								const newPane = { ...pane };
								if (newPane.key === dragLeft || newPane.key === dragRight) {
									newPane.top = dragBounds.top;
									newPane.right = dragBounds.right;
									newPane.bottom = dragBounds.bottom;
									newPane.left = dragBounds.left;

									if (axe === 'horizontal') {
										newPane[newPane.key === dragLeft ? 'bottom' : 'top'] = cY;
									} else {
										newPane[newPane.key === dragLeft ? 'right' : 'left'] = cX;
									}
								}
								panes.push(newPane);
								return panes;
							}, [] as PaneProps[]);

							onChange(newPanes);
							return;
						}
					}
				}

				if (dragLeft !== undefined && dragRight !== undefined) {
					const edge = layout.edges.find(e => e.left.id === dragLeft && e.right.id === dragRight);
					if (edge) {
						const p = edge.axe === 'horizontal' ? cY : cX;
						
						edge.p = p;
						edge.updateDOM();

						if (dragSiblings) {
							for (const sibling of edge.siblings) {
								sibling.p = p;
								sibling.updateDOM();
							}
						}
					}
				}
			}
		}

		window.addEventListener('resize', onResize);
		document.addEventListener('pointerup', onLeave);
		document.addEventListener('pointermove', onMove);
		return () => {
			window.removeEventListener('resize', onResize);
			document.removeEventListener('pointerup', onLeave);
			document.removeEventListener('pointermove', onMove);
		}
	}, [panes, onChange]);

	const onEdgeDown = (id: number) => (e: React.PointerEvent) => {
		e.preventDefault();
		e.stopPropagation();

		const edge = layout.edges[id];
		let minX: number = 0;
		let maxX: number = 100;
		let minY: number = 0;
		let maxY: number = 100;
		const breakable = edge.axe === 'horizontal'
			? Math.abs(edge.left.left - edge.right.left) < 0.1 && Math.abs(edge.left.right - edge.right.right) < 0.1
			: Math.abs(edge.left.top - edge.right.top) < 0.1 && Math.abs(edge.left.bottom - edge.right.bottom) < 0.1;

		for (const sibiling of [edge].concat(edge.siblings)) {
			minX = Math.max(minX, sibiling.left.left);
			maxX = Math.min(maxX, sibiling.right.right);
			minY = Math.max(minY, sibiling.left.top);
			maxY = Math.min(maxY, sibiling.right.bottom);
		}

		internal.current = {
			...internal.current!,
			dragging: true,
			dragLeft: edge.left.id,
			dragRight: edge.right.id,
			dragBounds: new DOMRect(minX, minY, maxX - minX, maxY - minY),
			dragSiblings: !(breakable && e.ctrlKey)
		};
	};

	const onDividerDown = (id: number, corner: Corner) => (e: React.PointerEvent) => {
		e.preventDefault();
		e.stopPropagation();

		const pane = layout.panes[id];

		const paneProps: PaneProps = panes.find(p => p.key === pane.id)!;
		const newPaneProps: PaneProps = { ...paneProps };
		newPaneProps.key = nanoid();

		let dragLeft = pane.id;
		let dragRight = newPaneProps.key;

		if (corner === 'top-left' || corner === 'bottom-left') {
			let t = dragLeft;
			dragLeft = dragRight;
			dragRight = t;
			paneProps.left += 1;
			newPaneProps.right = paneProps.left;
		} else {
			paneProps.right -= 1;
			newPaneProps.left = paneProps.right;
		}

		internal.current = {
			...internal.current!,
			dragging: true,
			dragLeft,
			dragRight,
			dragCorner: corner,
			dragBounds: new DOMRect(pane.left, pane.top, pane.right - pane.left, pane.bottom - pane.top),
			divAxe: 'vertical'
		};

		console.log('div', paneProps, newPaneProps, dragLeft, dragRight);

		onChange(panes.concat([newPaneProps]));
	};

	return (<div className="layout" ref={layoutRef}>
		<div className="layout-edge-container">
			{layout.edges.map((edge, id) => {
		let styles: React.CSSProperties = {};
		if (edge.axe === 'horizontal') {
			const left = Math.max(edge.left.left, edge.right.left);
			const right = Math.min(edge.left.right, edge.right.right);
			styles.top = edge.p.toFixed(6) + '%';
			styles.left = left.toFixed(6) + '%';
			styles.width = (right - left).toFixed(6) + '%';
			styles.height = 'var(--edge-size)';
		} else {
			const top = Math.max(edge.left.top, edge.right.top);
			const bottom = Math.min(edge.left.bottom, edge.right.bottom);
			styles.top = top.toFixed(6) + '%';
			styles.left = edge.p.toFixed(6) + '%';
			styles.width = 'var(--edge-size)';
			styles.height = (bottom - top).toFixed(6) + '%';
		}

		return <div
			ref={edge.ref}
			key={`edge-${edge.left.id}-${edge.right.id}`}
			className={`layout-handle-edge layout-handle-edge--${edge.axe}`}
			style={styles}
			onPointerDown={onEdgeDown(id)}
		/>;
	})}
		</div>
		<div className="layout-divider-container">
			{layout.panes.map((pane, id) => <div
		ref={pane.dividerRef}
		key={`divider-${pane.id}`}
		className="layout-handle"
		style={{
			top: `${pane.top.toFixed(6)}%`,
			right: `${(100 - pane.right).toFixed(6)}%`,
			bottom: `${(100 - pane.bottom).toFixed(6)}%`,
			left: `${(pane.left).toFixed(6)}%`,
			borderWidth: pane.links.map((link, dir) => link ? (dir === 1 || dir === 2 ? `var(--border-size)` : 0) : `var(--border-size)`).join(' ')
		}}
	>
		<div key="top-left" className={`layout-handle-divider layout-handle-divider--top-left`} onPointerDown={onDividerDown(id, 'top-left')} />
		<div key="top-right" className={`layout-handle-divider layout-handle-divider--top-right`} onPointerDown={onDividerDown(id, 'top-right')} />
		<div key="bottom-left" className={`layout-handle-divider layout-handle-divider--bottom-left`} onPointerDown={onDividerDown(id, 'bottom-left')} />
		<div key="bottom-right" className={`layout-handle-divider layout-handle-divider--bottom-right`} onPointerDown={onDividerDown(id, 'bottom-right')} />
	</div>)}
		</div>
		<div className="layout-view-container">
			{layout.panes.map((pane, id) => <div
		ref={pane.paneRef}
		key={`pane-${id}`}
		className="layout-view-container-view"
		style={{
			top: `${pane.top.toFixed(6)}%`,
			right: `${(100 - pane.right).toFixed(6)}%`,
			bottom: `${(100 - pane.bottom).toFixed(6)}%`,
			left: `${pane.left.toFixed(6)}%`,
			borderWidth: pane.links.map((link, dir) => link ? (dir === 1 || dir === 2 ? `var(--border-size)` : 0) : `var(--border-size)`).join(' ')
		}}
	>
		{pane.id}
	</div>)}
		</div>
	</div>);
}

const { abs, min, max } = Math;

class Layout {

	public edges: Edge[];
	public panes: Pane[];

	constructor(panesProps: PaneProps[]) {
		// Find neighbors
		const neighbors: [number[], number[], number[], number[]][] = [];
		for (let a = 0, b = panesProps.length; a < b; ++a) {
			const pane = panesProps[a];
			const neighbor: [number[], number[], number[], number[]] = [[], [], [], []];
			const pLeft = min(pane.left, pane.right);
			const pRight = max(pane.left, pane.right);
			const pTop = min(pane.top, pane.bottom);
			const pBottom = max(pane.top, pane.bottom);
			for (let c = 0, d = panesProps.length; c < d; ++c) {
				if (a !== c) {
					const other = panesProps[c];
					const oLeft = min(other.left, other.right);
					const oRight = max(other.left, other.right);
					const oTop = min(other.top, other.bottom);
					const oBottom = max(other.top, other.bottom);

					// TOP
					if (abs(pane.top - other.bottom) <= 0.1 && segmentIntersect(pLeft, pRight, oLeft, oRight)) {
						neighbor[0].push(c);
					}
					// RIGHT
					else if (abs(pane.right - other.left) <= 0.1 && segmentIntersect(pTop, pBottom, oTop, oBottom)) {
						neighbor[1].push(c);
					}
					// BOTTOM
					else if (abs(pane.bottom - other.top) <= 0.1 && segmentIntersect(pLeft, pRight, oLeft, oRight)) {
						neighbor[2].push(c);
					}
					// LEFT
					else if (abs(pane.left - other.right) <= 0.1 && segmentIntersect(pTop, pBottom, oTop, oBottom)) {
						neighbor[3].push(c);
					}
				}
			}
			neighbors.push(neighbor);
		}

		// Create edges
		const edges = neighbors.reduce((edges, neighbors, a) => {
			// RIGHT, BOTTOM only
			for (let dir = 1; dir < 3; ++dir) {
				for (const b of neighbors[dir]) {
					const axe = dir % 2 ? 'vertical' : 'horizontal';
					const pos = dir % 2 ? panesProps[a].right : panesProps[a].bottom;
					const key = `${Math.min(a, b)}-${Math.max(a, b)}`;
					if (!edges.has(key)) {
						if (pos === 0 || pos === 100) {
							debugger;
						}
						edges.set(key, new Edge(axe, pos, null!, null!, []));
					}
				}
			}
			return edges;
		}, new Map<string, Edge>());

		for (const [_, edge] of edges) {
			for (const [_, other] of edges) {
				if (edge !== other && edge.axe === other.axe && Math.abs(edge.p - other.p) < 0.1) {
					edge.siblings.push(other);
				}
			}
		}

		// Create panes
		const panes = neighbors.reduce((panes, neighbors, a) => {
			const pane = new Pane(panesProps[a].key, [[], [], [], []]);
			pane.links = neighbors.map((neighbors, dir) => {
				return neighbors.reduce((links, b) => {
					const key = `${Math.min(a, b)}-${Math.max(a, b)}`;
					if (edges.has(key)) {
						const edge = edges.get(key)!;
						edge[dir === 1 || dir === 2 ? 'left' : 'right'] = pane;
						links.push(edge);
					}
					return links;
				}, [] as Edge[]);
			}) as Links;
			panes.push(pane);
			return panes;
		}, [] as Pane[]);

		this.edges = Array.from(edges.values());
		this.panes = panes;
	}

	public dispose() {
		for (const edge of this.edges) {
			edge.dispose();
		}
		for (const pane of this.panes) {
			pane.dispose();
		}
		this.edges = undefined!;
		this.panes = undefined!;
	}
}

type Links = [Edge[], Edge[], Edge[], Edge[]];
type Corner = 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

class Edge {
	public ref: React.RefObject<HTMLDivElement>;

	constructor(
		public axe: Axe,
		public p: number,
		public left: Pane,
		public right: Pane,
		public siblings: Edge[],
	) {
		this.ref = React.createRef();
	}

	public dispose() {
		this.ref = undefined!;
		this.left = undefined!;
		this.right = undefined!;
		this.siblings = undefined!;
	}

	public updateDOM() {
		this.left.updateDOM();
		this.right.updateDOM();
		if (this.ref.current) {
			if (this.axe === 'horizontal') {
				const left = Math.max(this.left.left, this.right.left);
				const right = Math.min(this.left.right, this.right.right);
				this.ref.current.style.top = this.p.toFixed(6) + '%';
				this.ref.current.style.left = left.toFixed(6) + '%';
				this.ref.current.style.width = (right - left).toFixed(6) + '%';
				this.ref.current.style.height = 'var(--edge-size)';
			} else {
				const top = Math.max(this.left.top, this.right.top);
				const bottom = Math.min(this.left.bottom, this.right.bottom);
				this.ref.current.style.top = top.toFixed(6) + '%';
				this.ref.current.style.left = this.p.toFixed(6) + '%';
				this.ref.current.style.width = 'var(--edge-size)';
				this.ref.current.style.height = (bottom - top).toFixed(6) + '%';
			}
		}
		for (const sibling of this.siblings) {
			sibling.left.updateDOM();
			sibling.right.updateDOM();
		}
	}
}

class Pane {
	public paneRef: React.RefObject<HTMLDivElement>;
	public dividerRef: React.RefObject<HTMLDivElement>;

	constructor(
		public id: string,
		public links: Links
	) {
		this.paneRef = React.createRef();
		this.dividerRef = React.createRef();
	}

	public dispose() {
		this.paneRef = undefined!;
		this.dividerRef = undefined!;
		this.links = undefined!;
	}

	public updateDOM() {
		for (const ref of [this.paneRef, this.dividerRef]) {
			if (ref.current) {
				ref.current.style.top = `${this.top}%`;
				ref.current.style.right = `${100 - this.right}%`;
				ref.current.style.bottom = `${100 - this.bottom}%`;
				ref.current.style.left = `${this.left}%`;
			}
		}
	}

	get top(): number {
		return this.links[0].length ? this.links[0][0].p : 0;
	}

	get right(): number {
		return this.links[1].length ? this.links[1][0].p : 100;
	}

	get bottom(): number {
		return this.links[2].length ? this.links[2][0].p : 100;
	}

	get left(): number {
		return this.links[3].length ? this.links[3][0].p : 0;
	}

	get width(): number {
		return this.right - this.left;
	}

	get height(): number {
		return this.bottom - this.top;
	}
}

function segmentIntersect(x1: number, x2: number, y1: number, y2: number): boolean {
	return x2 > y1 && y2 > x1;
}
