// app2/client/Workbench.svelte
<script lang="ts">
	import Layout from './Layout.svelte';
</script>

<div class="workbench">
	<canvas id="mainCanvas" />
	<Layout panes={[
		{
			key: 'main',
			top: 0,
			right: 60,
			bottom: 100,
			left: 0,
			elem: 'Viewport'
		},
		{
			key: 'outline',
			top: 0,
			right: 100,
			bottom: 40,
			left: 60,
			elem: 'Outline'
		},
		{
			key: 'properties',
			top: 40,
			right: 100,
			bottom: 100,
			left: 60,
			elem: 'Properties'
		}
	]} />
</div>

<style>
	.workbench {
		display: flex;
		flex: 1;
	}

	canvas {
		position: absolute;
		width: 100%;
		height: 100%;
		z-index: 0;
		pointer-events: none;
		background: #333;
	}
</style>

// app/src/containers/Workbench.tsx
import React, { useState } from 'react';
import Layout from './Layout';

export default function Workbench() {

	const [panes, setPanes] = useState([
		{
			key: '0',
			top: 0,
			right: 50,
			bottom: 50,
			left: 0,
			elem: <div>0</div>
		}, {
			key: '1',
			top: 0,
			right: 100,
			bottom: 50,
			left: 50,
			elem: <div>1</div>
		}, {
			key: '2',
			top: 50,
			right: 50,
			bottom: 100,
			left: 0,
			elem: <div>2</div>
		}, {
			key: '3',
			top: 50,
			right: 100,
			bottom: 100,
			left: 50,
			elem: <div>3</div>
		}
		// {
		// 	key: '0',
		// 	top: 0,
		// 	right: 50,
		// 	bottom: 33.3333,
		// 	left: 0,
		// 	elem: <div>0</div>
		// }, {
		// 	key: '1',
		// 	top: 0,
		// 	right: 100,
		// 	bottom: 50,
		// 	left: 50,
		// 	elem: <div>1</div>
		// }, {
		// 	key: '2',
		// 	top: 33.3333,
		// 	bottom: 66.6666,
		// 	right: 25,
		// 	left: 0,
		// 	elem: <div>2</div>
		// }, {
		// 	key: '3',
		// 	top: 66.6666,
		// 	right: 50,
		// 	bottom: 100,
		// 	left: 0,
		// 	elem: <div>3</div>
		// }, {
		// 	key: '4',
		// 	top: 50,
		// 	right: 100,
		// 	bottom: 100,
		// 	left: 50,
		// 	elem: <div>4</div>
		// }, {
		// 	key: '5',
		// 	top: 33.3333,
		// 	bottom: 66.6666,
		// 	right: 50,
		// 	left: 25,
		// 	elem: <div>5</div>
		// }
	]);

	return (
		<Layout panes={panes} onChange={setPanes} />
	)
}
